server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Serve React app — all routes fall back to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API to Django
    location /api/ {
        proxy_pass http://umairu-svc:80/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy media to Django
    location /media/ {
        proxy_pass http://umairu-svc:80/media/;
        proxy_set_header Host $host;
    }
}