apiVersion: v1
kind: Secret
metadata:
  name: umairu-secrets
  namespace: umairu
type: Opaque
stringData:
  POSTGRES_DB: umairu
  POSTGRES_USER: umairu
  POSTGRES_PASSWORD: TQdPOnebDPuBiiiWaR7cSEOnSupr6OOpwYHqUUQblX8=
  DJANGO_SECRET_KEY: "1qD9iGsRG9zoe6et22QSzu8nqKAzZnyfdBy8Ktrw5Lb78NPi/fJ+SQ4ypqYGDbANNF9EkcMgok+wxtJ3h2wviw=="
  MINIO_ROOT_USER: umairu
  MINIO_ROOT_PASSWORD: TQdPOnebDPuBiiiWaR7cSEOnSupr6OOpwYHqUUQblX8=
