apiVersion: v1
kind: ConfigMap
metadata:
  name: umairu-config
  namespace: umairu
data:
  POSTGRES_HOST: postgres-svc
  POSTGRES_PORT: "5432"
  ALLOWED_HOSTS: "*"
  DEBUG: "false"
  MINIO_ENDPOINT: minio-svc:9000
  MINIO_BUCKET: umairu-media
  MINIO_USE_SSL: "false"